### ISSUE TITLE
Error performing callback 'prepare_guest' on auxiliary module 'Reboot'

### ISSUE THREAD

**Issue by thuanle9** [S4kur4/AutoDeployCuckoo#20]
Can you help to solve this problem with "reboot analysis" .tks.

2023-07-27 07:40:44,661 [cuckoo.core.plugins] ERROR: Error performing callback 'prepare_guest' on auxiliary module 'Reboot'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 145, in callback
    getattr(module, "cb_%s" % name, default)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/reboot.py", line 57, in cb_prepare_guest
    self._push_dropped_files(analysis_path)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/auxiliary/reboot.py", line 50, in _push_dropped_files
    self.guest_manager.post("/store", files=files, data=data)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/guest.py", line 339, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://192.168.56.5:8000/store
2023-07-27 07:42:50,230 [cuckoo.core.guest] INFO: cuckoo1: analysis completed successfully
2023-07-27 07:43:02,189 [cuckoo.core.scheduler] INFO: Task #12: reports generation completed
2023-07-27 07:43:02,196 [cuckoo.core.scheduler] INFO: Task #12: analysis procedure completed

![Error2](https://github.com/S4kur4/AutoDeployCuckoo/assets/140716986/fd15b9c0-b6b7-48cb-a2fc-9098115726b2)

**Comment by Jason-Cen** [comment]
when i RUN cuckoo, I got the following issues, can you please give me a hand. I follow you instructions to run the script.

jason@jason-virtual-machine:~$ cuckoo

                                 _|
     _|_|_|  _|    _|    _|_|_|  _|  _|      _|_|      _|_|
   _|        _|    _|  _|        _|_|      _|    _|  _|    _|
   _|        _|    _|  _|        _|  _|    _|    _|  _|    _|
     _|_|_|    _|_|_|    _|_|_|  _|    _|    _|_|      _|_|

 Cuckoo Sandbox 2.0.7
 www.cuckoosandbox.org
 Copyright (c) 2010-2018

2023-08-03 15:40:26,334 [cuckoo] ERROR: The maximum number of open files is low (4096). If you do not increase it, you may run into errors later on.
2023-08-03 15:40:26,334 [cuckoo] ERROR: See also: https://cuckoo.sh/docs/faq/index.html#ioerror-errno-24-too-many-open-files
 Checking for updates...
 Error checking for the latest Cuckoo version: HTTPSConnectionPool(host='cuckoosandbox.org', port=443): Max retries exceeded with url: /updates.json?version=2.0.7 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f019be8ce90>: Failed to establish a new connection: [Errno -2] Name or service not known',))!
2023-08-03 15:40:46,604 [cuckoo] WARNING: It appears that you haven't loaded any Cuckoo Signatures. Signatures are highly recommended and improve & enrich the information extracted during an analysis. They also make up for the analysis score that you see in the Web Interface - so, pretty important!
2023-08-03 15:40:46,604 [cuckoo] WARNING: You'll be able to fetch all the latest Cuckoo Signatures, Yara rules, and more goodies by running the following command:
2023-08-03 15:40:46,605 [cuckoo] INFO: $ cuckoo community
2023-08-03 15:40:46,607 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2023-08-03 15:40:48,329 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2023-08-03 15:40:48,337 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2023-08-03 15:44:42,092 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "FILES" (task #1, options "procmemdump=yes,route=none")
2023-08-03 15:44:42,129 [cuckoo.core.scheduler] INFO: Task #1: acquired machine cuckoo1 (label=cuckoo1)
2023-08-03 15:44:42,145 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 84514 (interface=vboxnet0, host=192.168.56.5)
2023-08-03 15:44:43,559 [cuckoo.core.guest] INFO: Starting analysis #1 on guest (id=cuckoo1, ip=192.168.56.5)
2023-08-03 15:47:44,317 [cuckoo.core.scheduler] ERROR: Error from machine 'cuckoo1': it appears that this Virtual Machine hasn't been configured properly as the Cuckoo Host wasn't able to connect to the Guest. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration
2023-08-03 15:47:46,091 [cuckoo.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2023-08-03 15:48:06,172 [cuckoo.processing.virustotal] WARNING: Error fetching results from VirusTotal for "8d18db8e6383baecd03c38590866f4b964505b14d3b627672e256197947287d9": Unable to fetch VirusTotal results: MaxRetryError("HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /vtapi/v2/file/report (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f01994bdc10>: Failed to establish a new connection: [Errno -2] Name or service not known',))",)
2023-08-03 15:48:06,173 [cuckoo.processing.debug] ERROR: Error processing task #1: it appears that the Virtual Machine hasn't been able to contact back to the Cuckoo Host. There could be a few reasons for this, please refer to our documentation on the matter: https://cuckoo.sh/docs/faq/index.html#troubleshooting-vm-network-configuration
2023-08-03 15:48:06,234 [cuckoo.core.scheduler] INFO: Task #1: reports generation completed
2023-08-03 15:48:06,239 [cuckoo.core.scheduler] INFO: Task #1: analysis procedure completed
